#!/bin/bash

XKB_DEFAULT_LAYOUT=us,ru
XKB_DEFAULT_OPTIONS=grp:caps_toggle,grp_led:scroll,compose:ralt
LANG="en_US.UTF-8"

PS1="\[\e[01;32m\]\u@\[\e[0m\]\[\e[00;33m\]\h\[\e[0m\]\[\e[00;37m\] in \[\e[0m\]\[\e[00;36m\]\w\[\e[0m\]\[\e[00;37m\] \[\e[0m\]\[\e[00;32m\]\n\\$\[\e[0m\]\[\e[00;37m\] \[\e[0m\]"
TERM=xterm-256color

HISTSIZE=""

VISUAL=vim
EDITOR=vim

export XKB_DEFAULT_LAYOUT XKB_DEFAULT_OPTIONS LANG PS1 TERM \
       HISTSIZE VISUAL EDITOR
